### ISSUE TITLE
Returning Empty Array.

### ISSUE THREAD

**Issue by Samir-OP** [vladdenisov/ytmusic-api#2]
Code:
```
const { YTMUSIC } = require("ytmusic");
const api = new YTMUSIC("COOKIE", "USER ID");
async function a() {
 let data = await api.search("boss bitch", { filter: "songs"})
 console.log(data)
}
a()
```

**Comment by Samir-OP** [comment]
and the `user id` is optional but if I don't add it I get the error: 
```
     this.userID = args.userID;
                           ^

TypeError: Cannot read property 'userID' of undefined
```

**Comment by vladdenisov** [comment]
I'm sorry, but i've tested it last time near july 2020. Since that time it may have changed. I'll take a look at it soon. Thanks for the issue!

**Comment by vladdenisov** [comment]
Yep, this was my fault. It should've been fixed now. Can you test it now, please?

**Comment by Samir-OP** [comment]
Now this error 
```
C:\Users\hacke\Desktop\hmm\node_modules\ytmusic\dist\lib\endpoints\Search.js:110
                    throw new Error(response.error.status);
                          ^
Error: PERMISSION_DENIED
```

**Comment by vladdenisov** [comment]
I don't know why you get `PERMISSION_DENIED` error, as I get another, because of YT changing response scheme. I'll take a deeper look at this problem. Could you, please, share your full code, except cookie?

**Comment by vladdenisov** [comment]
Basically, [this is new response](https://del.dog/ytmusicresponse.txt), it's sending. But in my browser I still get old-style response

**Comment by vladdenisov** [comment]
So now I fixed searching songs, and it should work without `userID`.  But you should use authUser from `x-goog-authuser` header.

**Comment by vladdenisov** [comment]
Could you test it now?
