### ISSUE TITLE
Cannot read property 'popup' of undefined

### ISSUE THREAD

**Issue by Sveagruva** [vladdenisov/ytmusic-api#5]
ytmusic/dist/lib/endpoints/Playlist.js 189 line
if I try to add song that already in a playlist it will give an error because response from api doesn't have openPopupAction

TypeError: Cannot read property 'popup' of undefined at...

**Comment by vladdenisov** [comment]
Fixed with c0422b88bfd246813fa3f3d6a7e192278a1f755c and e16bd5765f3d29b315efce944353d9c873b6abc3.
But also there is a question: should this action throw error or just return  `error` option in response and status `STATUS_FAILED`?

**Comment by Sveagruva** [comment]
I think it should throw error but there should be a way to distinguish errors like not passing required parameter or not having connection from errors that occur because of an api response

**Comment by Sveagruva** [comment]
thanks for fixing it so fast
